server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    register-default-servlet: true
    ## Session 過期時間，默認單位為 s
    session:
      timeout: 600
  port: 9090

spring:
  datasource:
#    driver-class-name: com.tandem.sqlmx.SQLMXDriver
#    url: "jdbc:sqlmx:"
#    hikari:
#      catalog: mallcat
#      schema: mallsch
    url: jdbc:sqlserver://localhost;databaseName=testmall;encrypt=true;trustServerCertificate=true
    username: boss
    password: boss
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /static/**
#    converters:
#      preferred-json-mapper: gson
  resources:
    static-locations: classpath:/static/
  ## Session 存儲方式
  session:
    store-type: none


# 自訂參數
custom:
#  osType: OSS
  osType: WIN

#spring.http.encoding.charset=UTF-8
#spring.http.encoding.force=true
#spring.http.encoding.enable=true
